Add a new config in HttpServerConfig to set sniHostCheck
prestodb/airlift pull request #62
Opened 2023-01-25 21:24 UTC by jingmeih

Add a new config http-server.https.sni-host-check to set the sniHostCheck without making it to true by default.

2023-01-25 21:26 UTC, tdcmeehan approved these changes

2023-01-25 21:37 UTC, tdcmeehan requested changes
Please update the unit test as well

2023-01-25 22:55 UTC, jingmeih commented
> Please update the unit test as well

Added the unit test in TestHttpServerConfig, at this moment it requires making additional changes in JettyHttpClient to test the functionality of sniHostCheck (https://github.com/airlift/airlift/pull/917/commits/6cf6dfcd16361831ac69297aed5588d2df7c698e) which is not required for this PR. This PR itself should be safe to land.

2023-01-26 19:34 UTC, tdcmeehan approved these changes

2023-01-26 19:35 UTC, merged