Upgrade Jetty from 9.4.14.v20181114 to 9.4.53.v20231009 to Address Security Vulnerabilities
prestodb/airlift pull request #86
Opened 2024-05-28 02:29 UTC by siddhuoo7

## Summary

This pull request upgrades the Jetty server dependency from version 9.4.14.v20181114 to 9.4.53.v20231009. This update addresses several known security vulnerabilities and includes numerous improvements and bug fixes.

## Details

- **Current Version**: 9.4.14.v20181114
- **New Version**: 9.4.53.v20231009

### Vulnerabilities Addressed

Upgrading to Jetty 9.4.53.v20231009 addresses multiple security vulnerabilities, including but not limited to:

- CVE-2020-27216: Path traversal in Jetty HttpURI
- CVE-2021-34428: Session fixation vulnerability in Jetty
- CVE-2021-28163: Improper input validation in Jetty
- CVE-2021-28165: Incorrect resource isolation in Jetty

### Improvements and Bug Fixes

In addition to security fixes, this upgrade includes several performance improvements and bug fixes. Notable changes are:

- Enhanced WebSocket handling
- Improved HTTP/2 support and stability
- Better compliance with HTTP standards
- Various memory leak fixes
- Performance optimizations and reduced CPU usage under high load

### Testing

Thorough testing has been conducted to ensure compatibility and stability with our existing application. Tests include:

- Unit tests

2024-07-02 20:09 UTC, tdcmeehan requested changes

2024-07-02 20:09 UTC, tdcmeehan commented on http-client/src/test/java/com/facebook/airlift/http/client/jetty/TestHttpClientLogger.java
> +            return null;
```suggestion
            throw new UnsupportedOperationException();
        }

        @Override
        public Object getTag()
        {
            throw new UnsupportedOperationException();
```

2024-07-02 20:09 UTC, tdcmeehan commented on http-client/src/test/java/com/facebook/airlift/http/client/AbstractHttpClientTest.java
> +            assertEquals(statusMessage, "OK");
This seems unexpected given the test setup in line 629:

https://github.com/prestodb/airlift/pull/86/files#diff-b12aefec31120bfb874f675ab6f392e781b389a8acffeafe4d54b71e4202c85bR629

2024-07-02 20:09 UTC, tdcmeehan commented on http-client/src/test/java/com/facebook/airlift/http/client/AbstractHttpClientTest.java
> +        String json = "{\"fuite\":\"apple\",\"hello\":\"world\"}";
Is this change needed?

2024-08-23 19:58 UTC, tdcmeehan commented
@siddhuoo7 are you still working on this PR?

2024-12-05 21:59 UTC, czentgr commented
@siddhuoo7 You probably want to finish this off. Do you need help with this?

2025-04-24 14:42 UTC, ZacBlanco commented
We have upgraded to Jetty 12 now, so many CVEs in question should be resolved.

2025-04-24 14:42 UTC, closed without merging